### PR TITLE
update dynamic objects

### PR DESCRIPTION
**Pull request by ProjectHSI**

### CODE REVIEW

**Comment by raphnet** [comment]
About this:

`Apparently compiling getopt1.c causes MXE to fail.*`

Before your changes to the makefiles, getopt1.c was not actually being used anywhere it seems. Commits:

68654cdcdd4f2815bd90ff95ade94688140c224f
94fec1b7f3bd029509b3efe3c2da426e6c2e166a
47e4bf6a44f1993bc3c1fbf00fc14f7b4b331732

So I think it would be cleaner to remove getopt1.c, rather than keep it around with an exception to the makefile. What do you think?

**Comment by ProjectHSI** [comment]
If it isn't used anywhere then it does seem like it's better to remove getopt1.c instead of putting a band aid fix and making sure it gets ignored.

**Comment by ProjectHSI** [comment]
~~Actually it is used???~~
~~getopt.h is included in main.c, excluding getopt1.c errors the build... Somehow.~~

**Comment by ProjectHSI** [comment]
wait nvm

**Comment by ProjectHSI** [comment]
I excluded the .h from the build.

**Comment by ProjectHSI** [comment]
#23

**Pull request merged**
