### PR TITLE
Modify dynamic OBJs

### PR DESCRIPTION
**Pull request by ProjectHSI**
This PR fixes dynamic OBJs for MXE builds and adds support for nested source code files.

Apparently compiling getopt1.c causes MXE to fail.

### CODE REVIEW

**Comment by ProjectHSI** [comment]
wait

**Comment by ProjectHSI** [comment]
ah great

**Comment by raphnet** [comment]
I see you are working on supporting nested source files? Is the project large enough for this? For small projects with so few files I tend to prefer all files in one directory...

There are also some issues with what I see here. I don't think you really want to have static variables in a .h, since every place where it will be included a separate instance of the variable will be created. (config.h).

Also in shared.h, the variables declared there should be marked "extern", and there should be one normal declaration in a source C file.

What are you working on by the way?

**Comment by ProjectHSI** [comment]
I had to nuke the whole fork since I messed it up so much so that's why stuff is missing.

Modify dynamic OBJs was meant to be what the PR described but I accidentally merged two branches that weren't meant to merged together so all the commits in there weren't meant to be in here. Oops.

The files you were described were meant to be for where I was converting the project to SDL2 since SDL1.2 is described as "Historic" and builds of it aren't easy to find (in DLL format). This lead to me moving the SDL-related code into it's own file, which needed variables from main.c to be moved into a new file so that I could do that.

The config.h header file was directly copy-pasted from main.c and I didn't get around to it to fix it up, probably same with the others as they were meant to be written to and their contents shared.

This PR will be resubmitted with it's intended changes of refactoring and fixing the dynamic OBJs code.

**Pull request closed without merging**
