### PR TITLE
dev/makefile-mxe/use-info

### PR DESCRIPTION
**Pull request by ProjectHSI**
I forgot to swap out the warning command for the info command. I was using it for debugging.

Also the commit is just straight up weird, I think it had something to do with the fact Git wasn't configured to run with sudo which I did to try and diagnose the problem, Git was acting weird with signing.

Here's the error if you have any idea.
```
warning: command not found
error: gpg failed to sign the data
fatal: failed to write commit object
```

### CODE REVIEW

**Comment by raphnet** [comment]
I'm sorry, but could you redo this commit with a message that makes sense?

**Comment by ProjectHSI** [comment]
clarification: replace $(warning) with $(info) in makefile.mxe.
Once again I just forgot to swap out $(warning) with $(info) when pushing.
Is this enough or would you like the commit name to be clarified

**Comment by raphnet** [comment]
Sorry to be a pain, but I would like the project's commit history to be clean and understandable when I type git log. As things are now, my terminal will scroll several pages contents that has nothing to do with what the commit actually is about.

Could you prepare a new pull request with the same change, but with a normal commit message?

**Comment by ProjectHSI** [comment]
Closed to comply with the request.

**Pull request closed without merging**
