### PR TITLE
Fix makefile.mxe

### PR DESCRIPTION
**Pull request by ProjectHSI**
Fixes various problems with makefile.mxe.

### CODE REVIEW

**Comment by raphnet** [comment]
Could you please leave Makefile.mxe as is instead of renaming it? I use the Makefile.mxe convention everywhere, and Makefile.something is common.

**Comment by ProjectHSI** [comment]
ok.

**Comment by raphnet** [comment]
Thank you!

**Comment by ProjectHSI** [comment]
You're welcome.
The renaming was so that editors could recognize the file correctly. Some editors did (vim) but VSCode didn't recognize it until I renamed it to MXE.Makefile. Not required and purely style anyways.

**Pull request merged**
