### PR TITLE
Feature/objs-rework

### PR DESCRIPTION
**Pull request by ProjectHSI**
Reworks the OBJS variable in shared.mk to be dynamic, instead of creating 2 source code files (one for .c/.cpp and one for .h) and adding it to the OBJs variable, only creating the two source code files is required.

### CODE REVIEW

**Comment by ProjectHSI** [comment]
^ Quick note here, ignore the Unverified status on those commits. I'm using VSCode on WSL2 and I haven't fully configured it to use GPG signing yet.

**Review by raphnet — COMMENTED** [review]
Is that doing what I think? i.e. Is it equivalent to doing make -j X where X is the number of source files? If so, I don't think I like this. I believe the person typing Make should be the one doing the choice of how many parallel compilers to run, not something built into the makefile.

**Comment by ProjectHSI** [comment]
^ as make processes arguments from first to last and doesn't allow overriding existing parameters, if serial builds were to be done it would just be `-j 1`.

**Comment by raphnet** [comment]
I'm sorry, are you saying that make -j 5 for instance does not compile 5 source files in parallel?

**Comment by ProjectHSI** [comment]
The above assumption is incorrect after testing.

MAKEFLAGS doesn't override options specified in the command line arguments, if you run `make -j 5`, it can not overwrite `-j 5`. Not specifying `-j 5` sets it to the number of object files that exist (a.k.a. number of CXX source files (not header files))

**Comment by raphnet** [comment]
So this line you added automatically starts as many jobs as there are source files, right?

```MAKEFLAGS += --jobs=$(words $(OBJS))```

My point is that by default, when I type Make without additional parameters, I expect only one job. We cannot know in advance what needs the user compiling the source has, and what resources (cpu/mem) that are willing to use for compiling. (I don't think we can assume everyone wants to start 11 jobs)

I believe it is best to let this decision be taken by the user (the person typing Make). If the user always wants -j 4 or more when they compile something, they can use a shell alias.

**Comment by ProjectHSI** [comment]
This behavior will be reverted shortly.

**Comment by raphnet** [comment]
Thank you!

Just curious, as it is the first time I ever encounter a makefile which automatically boosts the number of jobs to as many source files there are to compile... Has this become a common thing?

Perhaps some IDEs do this (possibly with a upper limit on the number of jobs however) but for a unix Makefile, this is the first time I see this.

**Comment by ProjectHSI** [comment]
I just thought of this as I thought it's a bit more convenient to build files in a big burst rather than building in serial, since it's faster although I could see it's benefits in reporting errors (it's easier to see what file is causing while problem, although gcc/g++ already reports the file, i assume in deeply nested files it could be beneficial.)

**Pull request merged**
